### ISSUE TITLE
Ran into issues when started "infra_up"

### ISSUE THREAD

**Issue by bqcao** [legalchrome/infra#1]
The infra installation seems succeeded on my Ubuntu box (failed on Mac). But when I ran "infra_up" on the Ubuntu box, I got this:

infra_up 
up called
restoring volumes from snapshots
ERROR: (gcloud.compute.disks.create) Could not fetch resource:
 - The resource 'projects/sanguine-signal-782/zones/us-central1-c/disks/es-patents-1-volume1' already exists

ERROR: (gcloud.compute.disks.create) Could not fetch resource:
 - The resource 'projects/sanguine-signal-782/zones/us-central1-c/disks/es-legal-1-volume' already exists

ERROR: (gcloud.compute.disks.create) Could not fetch resource:
 - The resource 'projects/sanguine-signal-782/zones/us-central1-c/disks/es-patents-1-volume2' already exists

ERROR: (gcloud.compute.disks.create) Could not fetch resource:
 - The resource 'projects/sanguine-signal-782/zones/us-central1-c/disks/es-patents-1-volume3' already exists

Traceback (most recent call last):
  File "/home/bcaolc/anaconda2/bin/infra_up", line 11, in <module>
    load_entry_point('infra', 'console_scripts', 'infra_up')()
  File "/home/bcaolc/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bcaolc/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bcaolc/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bcaolc/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bcaolc/workspace/legalchrome/infra/infra/cli.py", line 198, in up
    pool(restore_snapshot, CONFIG['snapshot_ids'])
  File "/home/bcaolc/workspace/legalchrome/infra/infra/cli.py", line 181, in pool
    pool.map(func, tasks)
  File "/home/bcaolc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/bcaolc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
subprocess.CalledProcessError: Command '['gcloud', 'compute', '--project=sanguine-signal-782', 'disks', 'create', 'es-legal-1-volume', '--zone=us-central1-c', '--type=pd-ssd', '--source-snapshot=es-legal-1-volume', '--size=1000GB']' returned non-zero exit status 1

**Comment by lukeforehand** [comment]
I deleted the volumes and ran infra_up again
